@startuml
class PersonInkomst {
    + Namn : string <<get>> <<set>>
    + Lön : int <<get>> <<set>>
    + Timmar : int <<get>> <<set>>
    + Timlön() : int
    + VisaTimlön() : void
}
class Program {
    {static} Main(args:string[]) : void
    {static} ReadInt() : int
}
@enduml
